# Specify REDIS_HOST/REDIS_PORT and QUEUE when running
FROM alpine:latest
RUN apk --update add redis
COPY ./worker.py /worker.py
COPY ./wait_for_job.sh /wait_for_job.sh

RUN chmod +x /wait_for_job.sh

CMD ["/wait_for_job.sh"]