# Specify REDIS_HOST and QUEUE when running
FROM alpine:latest
#FROM python:3
RUN apk --update add redis
COPY ./worker.py /worker.py
COPY ./wait_for_job.sh /wait_for_job.sh

RUN chmod +x /wait_for_job.sh

CMD ["/wait_for_job.sh"]
#CMD sh