apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-2
spec:
  completions: 10
  parallelism: 1
  template:
    metadata:
      name: job-wq-2
    spec:
      containers:
      - name: c
        image: jontejj/job-wq-2
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: QUEUE
          value: job1
      restartPolicy: OnFailure