apiVersion: batch/v1
kind: Job
metadata:
  name: job-producer-1
spec:
  completions: 10
  parallelism: 10
  template:
    metadata:
      name: job-producer-1
    spec:
      containers:
      - name: p
        image: job-producer-1:2
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: QUEUE
          value: job1
      restartPolicy: OnFailure